version: "3.7"
networks:
  bookie:

services:
  db:
    image: mysql:latest
    container_name: desafio-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: desafio
    networks:
      - bookie
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    container_name: desafio-app
    # restart: always
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/app
    depends_on:
      - db
    networks:
      - bookie

volumes:
  db_data: